### PR TITLE
Update container-linux-config-transpiler to v0.3.1

### PR DESCRIPTION
**Pull request by dghubble**
* Fix for changes in the ct ConvertAs2_0 name and args

### CODE REVIEW

**Comment by dghubble** [comment]
Hold up, this still doesn't build cleanly and there is no CI.

**Comment by dghubble** [comment]
Although this builds and passes tests, still don't merge this. I use this plugin for a project and the newly build plugin doesn't actually work w Terraform v0.9.6 while the old one did.

```
dial unix /tmp/plugin986057539|netrpc: connect: no such file or directory
```

**Comment by bloo** [comment]
@dghubble this is blocking me - https://groups.google.com/forum/#!topic/coreos-user/7BC7Th4X1pY - will this be remedied, or are we stuck?

**Comment by dghubble** [comment]
I've taken another crack at this.Let's only bump container-linux-config-transpiler v0.3.1 and its declared dependencies and pin every other dependency.

Allowing terraform dependencies to be updated is going to cause issues we need to resolve separately. Moreover, there isn't much incentive to bump the terraform dependency to say v0.9.11 as that would mean the terraform binary v0.9.11 would be needed to ensure runtime compatibility. We've hit this before.

**Comment by dghubble** [comment]
@bloo @crawford just updating container-linux-config-transpiler is not enough to solve your issue and not the aim of this PR.

From the container-linux-config-transpiler source, it appears the new templating feature changed `ConvertAs2_0_0(cfg)` to `ConvertAs2_0(cfg, platform)`. The platform determines which variables are substituted (i.e. different for azure vs ec2, etc.). For now, we should pass platform "" and I'll assign @dgonyeo to the option here to make the platform templating feature usable.

**Comment by dghubble** [comment]
There should be no changes in compatability wrt. Terraform versions. I've tested the new plugin build with my local Terraform v0.9.6 install.

**Comment by dghubble** [comment]
Filed https://github.com/coreos/bugs/issues/2049 for getting platform-specific variables.

**Pull request merged**
