### PR TITLE
Upgrade container-linux-config-transpiler to v0.5.0

### PR DESCRIPTION
**Pull request by dhensen**
I needed this because I was using the terraform provider together with a CoreOS 1548.2.0 which has Ignition 2.1.0 spec. My machine kept failing on boot, turned out that directories were not provisioned because the provider used an outdated ct version. I hope I did a good job... If not, let me know how I can improve this PR!

### CODE REVIEW

**Comment by dghubble** [comment]
New Container Linux images should accept Ignition v2.0.0 configs. I'd like to retain support and test coverage for v2.0.0 configs to continue to support a range of Container Linux versions, whereas v2.1.0 can only be used with new Container Linux images. At least until v2.1.0 is broadly available.

**Comment by dgonyeo** [comment]
FWIW v2.1.0 is supported in CL stable

**Comment by dghubble** [comment]
Crawford points out v2.1.0 support was added in 1465.0.0. If this tool starts producing v2.1.0 configs, we have that as a minimum required version.

**Comment by dghubble** [comment]
This was discussed and sounds like we're ok cutting releases of this tool that note a minimum version. This can be incorporated into v0.3.0.

rel https://github.com/coreos/matchbox/pull/670

**Pull request merged**
